travis:
  secure:
    BINSTAR_TOKEN: N2A96bkrSxAiWEf3itS4gRATDkvq0s7RQAmtDcBQ0GbkwVHeevhQtMMVyOn2RgAPWrhB6m1z1cT6sywOi4zd5ZBy6OFLB9ewD7UAjaUMlzfPN9XLLaoHtaUUICrjyqeYYfOmld0yZbFUs7y3MSoYfFWb/0Fs+i4ZLvkj3HJV6qinkZQzUbjcbMHSzUUXGAWcYXoRTK0aUpK1hqJCQeaL8tTwQEVao4y1ptq2GB6kZMMBpc1Ddkq7cPhZ8pVeKFGbuye3UwGU9iEU60cBIP8ht+/Wo1zKgi3+rOx0wFWSxCkiflq/fG96kfU+F7Cu/S7vYVA0QHBqcG2blWbtXkVN2rYb+FLXA4ziCU6l10NaTnugZQNVjXZbxxWsAzXBcakBn0xoiEcTQy4oSKLe5lAMfKeAfW5Oi/cfSJsIl2fkb6zkO0BPQaI8UqHx10s+2yajxxK43GSVo+xPjdgH54GFVY4UuNYnW+Slt1WmcpdHNFk9r1sAI0YQBMxY4RJvS/8Qo5PhbD+L4wIcxr31lJHoG6VbGsWYIHMSaG1hIXEXVvfbNQjHfLoJ87pkRdqAbdx48XVxUxs5Ry6wsatfrced/Kt7vxI6sjFzbB20cZzW3Wfvo7C/lK8lsfiQPdtG/A+fEizSPQ5y9SYVZ5+RBEk4Q84APqlQlT1oyk7IsAA2FHE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
