travis:
  secure:
    BINSTAR_TOKEN: Pyj6yrFbI7qz7tDIRkC9oqJFw09U8Ywm6dUAINOHCnG+gf2HJqI3rQ8KJec9GzacgUkzS+nRz+isps0/TC8KKbUHLm3s2Qwcfo51gaQpE8vtl2qLKExQ3p7UrZPgj/IPyReFzsT58JoFoYPsKT6Pzyw0NpjaQZXp9dHXd1Fe2hgg7p/M6G/Q/kX6D+f0sVk1p1ab/i+BW4CYJbNU4AWG6g0IflfGV09brhtwz1MBlcAbMv6xZC3YbGiq4Pr+Q8q6N37VbogaGv/WaJYx99EzKmjiZgupN/4lRlmnOAMMqVsnBSdzqUNE/1OvxzqN6O5xQkDhXNuzVjDJOvZOUtw46c7hihJMBC8LWgSLI/XIAyIBo7WU1fhmaRJEtZYp9bFCJe6epQe9+zc/y+ny+enypYYaYP/rdLWFbRfaugSL98ceMRFe4h+Kf0vgxsMnOBemcFwK6KwIaTVvOqVnDiaWsiw1aw3Os4QgRFaAdFu4nMzUW9TF9EEpNg5gKI1iWQ+R7jgZ0qUCIpbNWyP+nKaknLmBp8TxuuzAkTT6svczkHqiK3B4DCIdaQEfJTZiqCqtUg7F+uC2MaN9eqC7a9yK5dqutluaySfrkoljsJoipGVPSM9I0gwdDXQiFmrwrbHpjWvdxIEN6yZorzuhoyYfsR2sRt70jd/fehV1AONiBL4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
