travis:
  secure:
    BINSTAR_TOKEN: mCIEOnDZuePR4UeT3KQFSTWAfZVi37LY9QUGEQ4454T7pN0ec8Ilfeb8Nr6PObkPQc4UyhM3bPdfXZrYeEzPvG0tIVoz09yOgCJ9hXPcOcCQTdbdF6t1okErCyToswCv2ThLZVsiq+RoqePtDpL+pdyPFQ4QuduKkoxd/qlsZWrJDK73VZnwoRIq4Ih8Pds6jKuqbtU/egfmoeACqSnEQXkxUe3wFYJNAmqxGmzgepsflQbt3xZwyjnwB9iyWS4zTDgg4wxOfiI9dsTKlCGu4JIPZePKEwgvxhMLM8OoSC4MwKg2RHrQs+d367lv5+ygXXzu0PiI5Vmji8Sl+sZfgTCHE+LXdkRSHdQsnKoobvThWxe8qfpIQQGbm9Rqa2Q0Re+2nuYuysItfCJO1WK0I7pvKF1cxECe9y3HSKgX3mwoAntnWgUBTKYnuc6MXNZ9Tupu6XJiZA8XyL4w0fULk/uB+M+QoNphHsqQruPaUnlLzLBcDVxAdn0apdc3eOJkuTNN9vsK159srA/ewmF03O0NH2tld/tx5XMOMo8RBkdBpOULJ4YcIbWwX4CoXfThFZC/poRPed0ZTvhGrUfcxCSABUBSRiGqfHhapXOJSWuW9uZktOt/u4WSqhgBb1kl9hSWniikIwWtHLW4XgrTHM0eW3ngrfvvimCQhw8yq+g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
